name: pay_with_paystack
description: Flutter Plugin that enable users make Paystack payment with either Mobile Money or Card on the fly provided you use the secret key provided to you from Paystack
version: 1.0.10
homepage: https://github.com/popekabu

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.1"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  uuid: ^3.0.1
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
